### PR TITLE
XPath filters

### PR DESCRIPTION
**Pull request by divergentdave**
I got nerd sniped by #52, here are XPath filters for XML and HTML documents. Tests are included, and I updated the browser files.

### CODE REVIEW

**Comment by konklone** [comment]
I was not expecting this at all. This is one of the most useful things I think citation.js could do, and it had totally run aground -- thanks for completely solving all of the problems inherent in it, and for adding unit tests. I will formally review this within the next 2 days, and publish a release to npm.

**Comment by konklone** [comment]
Are there any circumstances in which the `xpath_html` and `xpath_xml` filters will differ in output on a given input? In basic testing, they appear to function identically.

**Comment by konklone** [comment]
Again, fantastic work -- I added some documentation to the `README` for the feature (and for the `lines` filter).

@divergentdave, just let me know if you want commit access to this repo, if you feel like doing any more work. =)

@JoshData @gullicksonk Do you think this feature might have any applicability to https://uslaw.link or to the House' bill drafting functions? Here's how this works:

```
cite --pretty --filter=xpath_xml "
<?xml>
<document>
  <title>Best Bill of 2012</title>
  <bill>
    <introduction>Bill to enforce happiness amongst all the children</introduction>
    <closing>All information releasable through 5 U.S.C. 552 is now banned</closing>
    <footer>(c) Congress</footer>
  </bill>
</document>
"
```

```json
{
  "citations": [
    {
      "type": "usc",
      "match": "5 U.S.C. 552",
      "index": 35,
      "citation": "5 U.S.C. 552",
      "usc": {
        "title": "5",
        "section": "552",
        "subsections": [],
        "id": "usc/5/552"
      },
      "xpath": "/document[1]/bill[1]/closing[1]/text()[1]"
    }
  ]
}
```

This could be used to take a given XML input, detect citations that appear in any leaf text node in the document, and use the returned `xpath` and `index` fields to mark the XML document up in-place with citation information.

**Comment by divergentdave** [comment]
The biggest difference between the two filters is how the parsers deal with fragments. The HTML parser will wrap any fragment in the required &lt;html&gt; and &lt;body&gt; tags, while the XML parser will not. (see below) This was the motivating case that drove me to make two separate filters, but there will be a lot more edge cases, of course.

```bash
pi@raspberrypi ~/citation $ bin/cite --filter=xpath_html "1 U.S.C. 1"
{
  "citations": [
    {
      "type": "usc",
      "match": "1 U.S.C. 1",
      "index": 0,
      "citation": "1 U.S.C. 1",
      "usc": {
        "title": "1",
        "section": "1",
        "subsections": [],
        "id": "usc/1/1"
      },
      "xpath": "/html[1]/body[1]/text()[1]"
    }
  ]
}
pi@raspberrypi ~/citation $ bin/cite --filter=xpath_xml "1 U.S.C. 1"
{
  "citations": [
    {
      "type": "usc",
      "match": "1 U.S.C. 1",
      "index": 0,
      "citation": "1 U.S.C. 1",
      "usc": {
        "title": "1",
        "section": "1",
        "subsections": [],
        "id": "usc/1/1"
      },
      "xpath": "/text()[1]"
    }
  ]
}

```

**Comment by JoshData** [comment]
It might be handy when displaying bill text, since citations aren't always marked up at the source (even though they are supposed to be). For uslaw.link I'm not sure. Wasn't planning on a fixed-this-document-for-you mode, but maybe. :)

**Pull request merged**
